from flask import Flask, render_template, request,jsonify

app = Flask(__name__, template_folder="templates", static_folder="static")

@app.route("/")
def home():
    return render_template("index.html")
    
@app.route("/predict#search-bar-zone", methods=['POST'])
def predict():
    if request.method == 'POST':
        url_send = request.form['url']
        print(url_send)
    return render_template('index.html', prediction_text=url_send)


    
# if __name__ == "__main__":
#     app.run(debug=True)

#     @app.route('/', methods=['GET', 'POST'])
# def index():
#     if request.method == 'POST':
#         # Process the form data and generate the website content here
#         website_content = generate_website_content()
#         return website_content

#     # Render the initial HTML template (e.g., index.html)
#     return render_template('index.html')

# def generate_website_content():
#     # Replace this with your logic to generate the website content
#     # You can retrieve data from the form, a database, or any other source
#     # Return the HTML content for the website
#     return "<h2>Website Content</h2><p>This is the dynamic content generated by Flask.</p>"

# @app.route('/', methods=['GET', 'POST'])
# def index():
#     if request.method == 'POST':
#         # Get the text input from the form
#         user_input = request.form.get('user_input')
#         return jsonify({'result': user_input})
#     return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)